/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package iss2021_resumablebw;

import iss2021_resumablebw.annotations.ArilRobotSpec;
import iss2021_resumablebw.consolegui.ConsoleGui;
import iss2021_resumablebw.interaction.IssOperations;
import iss2021_resumablebw.supports.IssCommSupport;
import iss2021_resumablebw.supports.RobotApplicationStarter;
import iss2021_resumablebw.wenv.RobotInputController;

@ArilRobotSpec
public class ResumableBoundaryWalker {
    private RobotInputController controller;
    private ConsoleGui consoleGui;

    public ResumableBoundaryWalker(IssOperations rs) {
        IssCommSupport rsComm = (IssCommSupport) rs;
        controller = new RobotInputController(rsComm, true, true);
        consoleGui = new ConsoleGui(controller);
        rsComm.registerObserver(controller);
    }

    public void start() {
        controller.doBoundary();
    }

    public static void main(String args[]) {
        try {
            ResumableBoundaryWalker appl = (ResumableBoundaryWalker) RobotApplicationStarter.createInstance(ResumableBoundaryWalker.class);
            appl.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
