/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.wenvusage;

public class App {
    public String getGreeting() {
        return "Hello World, Daniele!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
