/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package iss2021_resumablebw;

import org.junit.Test;
import static org.junit.Assert.*;

public class ResumableBoundaryWalkerTest {
    @Test public void testAppHasAGreeting() {
        assertNotNull("app should have a greeting", "");
    }
}
